export const styles = {
  tabbtn: {
    width: { md: "177px", xs: "120px" },
    height: "37px",
    borderRadius: "16px",
    backgroundColor: "#EFF6FF",
    color: "#4fa9ff",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "18px",
    textTransform: "capitalize",
    mt: { md: "15px" },
  },
  tabactive: {
    width: { md: "177px", xs: "120px" },
    height: "37px",
    borderRadius: "16px",
    background:
      "linear-gradient(180deg, #4F9AFF 0%, #5CB6F2 99.99%, #5CB6F2 100%)",
    color: "#ffff",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "18px",
    textTransform: "capitalize",
    mt: { md: "15px" },
  },
  btns: {
    display: { xs: "flex" },
    flexWrap: "wrap",
    gap: "15px",
    justifyContent: "center",
  },
  companylogo: {
    width: "130px",
    height: "130px",
    background: "#EFF6FF",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
    m: "60px 0px 40px 40px",
  },
  logotxt: {
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "23px",
  },
  logosec: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
  },
  basictit: {
    m: "20px 0px 25px 35px",
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "23px",
    flexDirection: "row",
  },
  basictit2: {
    m: "45px 0px 5px 35px",
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "23px",
  },
  basictit1: {
    m: "30px 0px 30px 35px",
    fontWeight: "700",
    fontSize: "20px",
    lineHeight: "23px",
  },
  naminput: {
    width: { md: "100%", xs: "100%" },
    // marginLeft: "40px",
    height: "60px",
    color: "#BAD4DF",
    backgroundColor: "white",
  },
  naminputs1: {
    position: "fixed",
    marginLeft: "10px",
  },
  naminput1: {
    width: { md: "290px", xs: "200px" },
    // marginLeft:'40px',
    height: "60px",
    color: "black",
  },
  naminput2: {
    width: "100%",
    height: "60px",
    color: "black",
  },
  inputgrp: {
    display: "flex",
    flexWrap: "wrap",
    gap: "30px",

    mb: "35px",
  },
  sectxt: {
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "18px",
    mb: "8px",
    mt: "10px",
    color: "#034275",
  },
  sectxtloca: {
    marginLeft: "3rem",
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "18px",
    mb: "8px",
    mt: "20px",
  },
  sectxtloca1: {
    // marginLeft: "3rem",
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "18px",
    mb: "8px",
    mt: "20px",
  },
  addbtn: {
    textTransform: "capitalize",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ml: { sm: "5px", xs: "0px" },
  },
  addbtn2: {
    maxWidth: "160px",
    left: "50rem",
  },
  infofld: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%%",
    mt: "20px",
    // ml: "40px",
  },
  infofldloc: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  infofldadd: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    ml: "50px",
  },
  nxtbtn: {
    width: "160px",
    height: "60px",
    background: "linear-gradient(180deg, #4F9AFF 0%, #5CB6F2 100%)",
  },
  prvbtn: {
    width: "160px",
    height: "60px",
    color: "#4F9AFF",
  },

  nxtbox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    m: "65px 0 45px 0",
    gap: "15px",
  },
  addtxt: {
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "20px",
    padding: "20px",
    mt: "20px",
    ml: "15px",
    mb: "30px",
  },
  membox: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    // marginRight: " 40px",
  },
  membercard: {
    width: "400px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    p: "20px",
    mt: "20px",
    ml: "40px",
    boxShadow: "none",
  },
  headmem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  namebox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selctbtn: {
    fontWeight: 700,
    fontSize: "10px",
    lineHeight: "11px",
    color: "#4fa9ff",
    textTransform: "capitalize",
  },
  phototit: {
    fontWeight: 700,
    fontSize: "32px",
    lineHeight: "37px",
    textAlign: "center",
    mt: "35px",
  },
  photosub: {
    fontWeight: 400,
    fontSize: "20px",
    lineHeight: "23px",
    textAlign: "center",
    mt: "10px",
  },
  uploadphoto: {
    height: "357px",
    backgroundColor: "#EFF6FF",
    borderRadius: "16px",
    border: "2px dashed #4F9AFF",
    m: "28px 30px 0 30px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: "20px",
  },
  brwsbtn: {
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "50px",
    width: "168px",
    height: "62px",
    backgroundColor: "#4fa9ff",
    textTransform: "capitalize",
  },
  uptxt: {
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "50px",
    color: "#6a6a6a",
    p: "20px",
  },
  filetxt: {
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "18px",
  },
  pertxt: {
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "18px",
    color: "#6a6a6a",
  },
  uplodbox: {
    width: "500px",
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  jpg: {
    display: "flex",
    justifyContent: "space-between",
  },
  uploadfull: {
    display: "flex",
    rowGap: "40px",
    flexWrap: "wrap",
    justifyContent: "space-around",
  },
  prvbasic: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    p: "20px",
  },
  prvedit: {
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "18px",
    textTransform: "capitalize",
    color: "#4F9AFF",
  },
  bastext: {
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "18px",
  },
  logotxtprv: {
    fontWeight: "700",
    fontSize: "14px",
    lineHeight: "16px",
    color: "#6a6a6a",
  },
  prvname: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    p: "15px",
    ml: "15px",
  },
  prvnametext: {
    fontWeight: "700",
    fontSize: "14px",
    lineHeight: "16px",
    color: "#6a6a6a",
    width: "300px",
  },
  prvnametextinfo: {
    fontWeight: "700",
    fontSize: "14px",
    lineHeight: "16px",
    color: "#6a6a6a",
    width: "300px",
  },
  previewcard: {
    backgroundColor: "#EFF6FF",
    m: { xs: "25px", sm: "auto" },
  },
  socialcard: {
    m: "25px",
    borderRadius: "16px",
    boxShadow: "none",
  },
  prvnametab: {
    display: "flex",
    flexWrap: "wrap",
  },
  itbox: {
    display: "flex",
    flexWrap: "wrap",
    columnGap: "100px",
  },
  socbox: {
    display: "flex",
    flexWrap: "wrap",
    p: "10px",
  },
  memtitle: {
    fontWeight: "700",
    fontSize: "14px",
    lineHeight: "16px",
    color: "#6a6a6a",
    p: "15px",
  },
  memscard: {
    background: "#ffff",
    width: "300px",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
  },
  bluboxmem: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    justifyContent: "center",
    pb: "10px",
  },
  mainmembox: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
    rowGap: "15px",
    mb: "20px",
  },
  bluememtext: {
    fontWeight: "700",
    fontSize: "12px",
    lineHeight: "16px",
    color: "#4F9AFF",
    textAlign: "center",
  },
  imgmainbox: {
    display: "flex",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
    gap: "15px",
    mb: "15px",
  },
  imgcard: {
    background: "#ffff",
    width: "200px",
    borderRadius: "16px",
    border: "1px solid #4F9AFF",
    overflow: "hidden",
  },
  photoname: {
    fontWeight: "400",
    fontSize: "14px",
    lineHeight: "16.1px",
    color: "#6A6A6A",
  },
  boxphoto: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    p: "10px",
  },
  photosrend: {
    borderTopRightRadius: "16px",
    borderTopLeftRadius: "16px",
    width: "200px",
    objectFit: "contain",
    height: "90px",
  },

  addBtns: {
    // position: "absolute",
    // marginBottom: "5rem",
    // marginRight: "13rem",
    // padding:{mt:"0px",mb: "0px"},
    color: "#fff",
    borderRadius: "10px",
    backgroundColor: "#4fa9ff",
  },
  addBtnss: {
    position: "absolute",
    marginBottom: "7rem",
    // marginRight: "8rem",
    // padding:{mt:"0px",mb: "0px"},
    color: "#fff",
    borderRadius: "10px",
    backgroundColor: "#4fa9ff",
  },
};
