export const styles = {
  progressbox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    p: "15px",
  },
  linebox: {
    display: "flex",
    gap: "5px",
    alignItems: "center",
  },
  addtxt: {
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "20px",
    padding: "15px",
    mt: "20px",
    ml: "15px",
  },
  infofldloc: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    ml: "40px",
  },

  naminput2: {
    width: "100%",
    height: "56px",
    color: "black",
  },
  infofld: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
  },

  sectxt: {
    fontWeight: "700",
    fontSize: "16px",
    lineHeight: "30px",
    mb: "8px",
    mt: "20px",
    color: "#4a4a4a",
  },
  naminput: {
    width: { md: "330px", xs: "200px" },
    height: "60px",
    color: "black",
  },
  salarinput: {
    width: { md: "160px", xs: "100px" },
    height: "60px",
    color: "black",
  },

  titlebox: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
  },
  descpboxmain: {
    display: "flex",
    flexWrap: "wrap",
  },
  bluetxt: {
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "18px",
    color: "#4fa9ff",
  },
  roleblue: {
    background: "#EFF6FF",
    width: { lg: "200px", xs: "150px" },
    p: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "16px",
    cursor: "pointer",
  },
  roleblue2: {
    width: { lg: "200px", xs: "150px" },
    p: "5px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "16px",
    border: "1px solid #4F9AFF",
    textTransform: "capitalize",
  },
  rolesbox: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: "20px",
    p: "10px",
    ml: "30px",
  },
  salarybox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    ml: "40px",
    width: "100%",
  },
  salarymain: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
  },
  nxtbtn: {
    width: "160px",
    height: "60px",
    background: "linear-gradient(180deg, #4F9AFF 0%, #5CB6F2 100%)",
  },
  prvbtn: {
    width: "160px",
    height: "60px",
    color: "#4F9AFF",
  },
  nxtbox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    m: "65px 0 45px 0",
    gap: "15px",
  },
  previewcard: {
    backgroundColor: "#EFF6FF",
    m: "25px",
    border: "1px solid #4F9AFF",
    borderRadius: "16px",
    boxShadow: "none",
  },
  prvbasic: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    p: "20px",
  },
  bastext: {
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "18px",
  },
  headingprv: {
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "18px",
    color: "#6a6a6a",
    textAlign: "left",
    width: { md: "200px", xs: "110px" },
  },
  contentprv: {
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "18px",
    textAlign: "left",
    width: { md: "200px", xs: "120px" },
  },
  prvskillstext: {
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "18px",
    textAlign: "center",
    background: "#ffff",
    width: "90px",
    borderRadius: "8px",
    color: "#4fa9ff",
    p: "5px",
  },
  prvskillsbox: {
    width: "200px",
    display: "flex",
    gap: "5px",
  },
  prevtextbox: {
    display: "flex",
    justifyContent: "space-between",
    p: "10px",
    gap: { lg: "140px", md: "100px", xs: "0px" },
    alignItems: "center",
    ml: "20px",
  },
  essentialbox: {
    display: "flex",
    flexWrap: "wrap",
  },
  quesheadbox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    p: "15px",
    pl: "20px",
    pr: "20px",
  },
  quesheadtxt: {
    fontWeight: 700,
    fontSize: "20px",
    lineHeight: "23px",
    // textAlign:'left'
    mt: "15px",
  },
  quesfield: {
    width: "90%",
    // pr: "20px",
    // pl: "20px",
    backgroundColor: "white",
    ml: "5%",
    mr: "5%",
  },
  radiofield: {
    display: "flex",
    mt: "20px",
    // margin:'auto'
    pl: "80px",
    pr: "20px",
  },
  addbtn: {
    display: "flex",
    justifyContent: "flex-end",
    mr: "20px",
    mt: "10px",
  },
  questbox: {
    background: "#F1F3F6",
    m: "15px",
  },

  outinp: {
    width: { xl: "900px", lg: "800px", md: "500px", sm: "400px", xs: "150px" },
    background: "white",
  },
  addflbtn: {
    display: "flex",
    flexDirection: "column",
    textTransform: "capitalize",
    color: "#6a6a6a",
    p: "20px",
    cursor: "pointer",
    boxShadow: 1,
  },
  addflbtnbox: {
    display: "flex",
    justifyContent: "space-around",
    mt: "50px",
    flexWrap: "wrap",
  },
};
