export const EDUCATION_LEVELS = [
  "Doctorate",
  "Master’s degree",
  "Postgraduate Diploma",
  "Postgraduate Certificate",
  "Graduate with Honors",
  "Bachelor’s degree",
  "Graduate Diploma",
  "Diploma",
  "Certificate",
  "High school",
  "Elementary school",
];

export const LANGUAGES = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Asturian",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Catalan",
  "Central Kurdish",
  "Chinese",
  "Chinese (Hong Kong)",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Corsican",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "English (Australia)",
  "English (Canada)",
  "English (India)",
  "English (New Zealand)",
  "English (South Africa)",
  "English (United Kingdom)",
  "English (United States)",
  "Esperanto",
  "Estonian",
  "Faroese",
  "Filipino",
  "Finnish",
  "French",
  "French (Canada)",
  "French (France)",
  "French (Switzerland)",
  "Galician",
  "Georgian",
  "German",
  "German (Austria)",
  "German (Germany)",
  "German (Liechtenstein)",
  "German (Switzerland)",
  "Greek",
  "Guarani",
  "Gujarati",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Interlingua",
  "Irish",
  "Italian",
  "Italian (Italy)",
  "Italian (Switzerland)",
  "Japanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Korean",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Lingala",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maltese",
  "Marathi",
  "Mongolian",
  "Nepali",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Occitan",
  "Oriya",
  "Oromo",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Quechua",
  "Romanian",
  "Romanian (Moldova)",
  "Romansh",
  "Russian",
  "Scottish Gaelic",
  "Serbian",
  "Serbo",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Southern Sotho",
  "Spanish",
  "Spanish (Argentina)",
  "Spanish (Latin America)",
  "Spanish (Mexico)",
  "Spanish (Spain)",
  "Spanish (United States)",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tigrinya",
  "Tongan",
  "Turkish",
  "Turkmen",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Vietnamese",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

// Denominations Thousand, Lakh, Million, Crore, Billion
export const THOUSAND = "Thousand";
export const LAKH = "Lakh";
export const MILLION = "Million";
export const CORE = "Crore";
export const BILLION = "Billion";

export const DENOMINATIONS = [THOUSAND, LAKH, MILLION, CORE];

export const WORK_PREFERENCE = ["Remote", "Onsite", "Hybrid"];

export const JOB_NATURE = [
  "Full-time",
  "Contract",
  "Part-time",
  "Internship",
  "Temporary",
];

/**
 * Constants for alerts
 */
export const SUCCESS = "success";
export const ERROR = "error";

export const INTERMEDIATE = "intermediate";
export const EXPERT = "expert";
export const BEGINNER = "beginner";

export const LEVELS = [INTERMEDIATE, EXPERT, BEGINNER];

export const NOTICE_PERIODS = [
  "Immediate Joiner",
  "15 Days",
  "30 days",
  "45 Days",
  "60 Days",
  "90 Days",
];

export const USER_EXPERIENCES = [
  "Fresh",
  "Less than 1 year",
  "1+ Years",
  "2+ Years",
  "3+ Years",
  "4+ Years",
  "5+ Years",
  "6+ Years",
  "7+ Years",
  "8+ Years",
  "10+ Years",
  "15+ Years",
  "20+ Years",
];

// Data formats
export const YEARS = "YYYY";
export const YYYY_MM_DD = "YYYY/MM/DD";
export const SECTORS = [
  "Accounting, Banking and Finance",
  "Airlines / Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel / Fashion",
  "Architecture / Planning",
  "Arts / Crafts",
  "Automotive",
  "Aviation / Aerospace",
  "Mortgage",
  "Biotechnology / Greentech",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies / Equipment",
  "Capital Markets / Hedge Fund / Private Equity",
  "Chemicals",
  "Civic / Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software / Engineering",
  "Computer / Network Security",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense / Space",
  "Design",
  "E - Learning",
  "Education Management",
  "Electrical / Electronic Manufacturing",
  "Entertainment / Movie Production",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food Production",
  "Food / Beverages",
  "Fundraising",
  "Furniture",
  "Gambling / Casinos",
  "Glass / Ceramics / Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design / Web Design",
  "Health / Fitness",
  "Higher Education / Acadamia",
  "Hospital / Health Care",
  "Hospitality",
  "Human Resources / HR",
  "Import / Export",
  "Individual / Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology / IT",
  "Insurance",
  "International Affairs",
  "International Trade / Development",
  "Internet",
  "Investment Banking / Venture",
  "Investment Management / Hedge Fund / Private Equity",
  "Judiciary",
  "Law Enforcement",
  "Law Practice / Law Firms",
  "Legal Services",
  "Legislative Office",
  "Leisure / Travel",
  "Library",
  "Logistics / Procurement",
  "Luxury Goods / Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Market Research",
  "Marketing / Advertising / Sales",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Equipment",
  "Medical Practice",
  "Mental Health Care",
  "Military Industry",
  "Mining / Metals",
  "Motion Pictures / Film",
  "Museums / Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers / Journalism",
  "Non - Profit / Volunteering",
  "Oil / Energy / Solar / Greentech",
  "Online Publishing",
  "Other Industry",
  "Outsourcing / Offshoring",
  "Package / Freight Delivery",
  "Packaging / Containers",
  "Paper / Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary / Secondary Education",
  "Printing",
  "Professional Training",
  "Program Development",
  "Public Relations / PR",
  "Public Safety",
  "Publishing Industry",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate / Mortgage",
  "Recreational Facilities / Services",
  "Religious Institutions",
  "Renewables / Environment",
  "Research Industry",
  "Restaurants",
  "Retail Industry",
  "Security / Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing / Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation / Localization",
  "Transportation",
  "Utilities",
  "Venture Capital / VC",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine / Spirits",
  "Wireless",
  "Writing / Editing",
];

export const CAREER_LEVEL = [
  "Board",
  "Co-founder/partner",
  "Executives/C-suites",
  "Director/VP",
  "Manager/Senior Manager",
  "Architects/Senior Architects",
  "Tech Lead/Team Leader",
  "Senior Professional",
  "Junior Professional",
  "Fresher",
  "Intern",
];

export const NoticePeriod = [
  "Immediate Joiner",
  "15 Days",
  "30 days",
  "45 Days",
  "60 Days",
  "90 Days",
];

//Packages
export const FREE = "Free";
export const PRO = "Pro Plan";
export const PREMIUM = "Premium";
export const CONTACT = "Contact Us";
export const GROWTH = "Growth";
export const GOLD = "Gold";
export const JOB_POST = "job post";
export const JOB_SLOT = "job slot";

export const FREE_PACKAGE = {
  name: FREE,
  packageList: [
    "3 Free job posts",
    "Up to 3 candidates from candidate database",
    "Job expires in 1 month",
  ],
  pricing: {
    rs: null,
    us: null,
  },
  type: JOB_POST,
};

export const PRO_PLAN = {
  name: PRO,
  packageList: [
    "1 Job post",
    "Unlimited job applicants",
    "10 relevant profiles from the candidate database",
    "Job expires in 1 month",
    "10% off for more than 5 job posts",
  ],
  pricing: {
    rs: 600,
    us: 15,
  },
  type: JOB_POST,
};

export const PREMIUM_PACKAGE = {
  name: PREMIUM,
  packageList: [
    "1 Featured job post",
    "Unlimited job applicants",
    "Priority in job searches",
    "Marketing on Recroot social media handles",
    "20 relevant profiles from the candidate database",
    "Dedicated candidate manager",
    "Job expires in 1 month",
    "10% off for more than 5 job posts",
  ],
  pricing: {
    rs: 1600,
    us: 35,
  },
  type: JOB_POST,
};

export const GROWTH_PACKAGE = {
  name: GROWTH,
  packageList: [
    "1 Job slot",
    "1 Job active at a time",
    "Any number of job posts in draft status",
    "Guaranteed candidate selection",
    "Access to the candidate database",
    "Billed monthly",
  ],
  pricing: {
    rs: null,
    us: 1062,
  },
  type: JOB_SLOT,
};

export const GOLD_PACKAGE = {
  name: GOLD,
  packageList: [
    "5 Job slots",
    "5 Job active at a time",
    "2 Featured job slots",
    "Any number of job posts in draft status",
    "Dedicated candidate manager",
    "Access to the candidate database",
    "Billed monthly",
  ],
  pricing: {
    rs: null,
    us: 4956,
  },
  type: JOB_SLOT,
};

export const CONTACT_PACKAGE = {
  name: CONTACT,
  packageList: [
    "End to end recruitment service by Recroot.",
    "With dedicated technical recruiters, we recruit the right professionals as per your requirements on your behalf.",
    "Contact Us to know more. grow@arinnovate.io",
  ],
  pricing: {
    rs: null,
    us: null,
  },
};

export const NEW_PRICING_PLAN = {
  [FREE]: FREE_PACKAGE,
  [PRO]: PRO_PLAN,
  [PREMIUM]: PREMIUM_PACKAGE,
  [GROWTH]: GROWTH_PACKAGE,
  [GOLD]: GOLD_PACKAGE,
};

export const CANDIDATE = "Candidate";

export const SHORT_LISTED = "shortlist";
export const REJECTED = "rejected";
export const UNVIEW = "unview";
export const VIEWED = "viewed";
export const EMPLOYEE_STATUS = [SHORT_LISTED, REJECTED, UNVIEW, VIEWED];

export const TIME_ZONES = [
  "UTC-11:00-Midway Island",
  "UTC-10:00-Hawaii",
  "UTC-08:00-Alaska",
  "UTC-07:00-Baja California",
  "UTC-07:00-Pacific Time US and Canada)",
  "UTC-07:00-Arizona",
  "UTC-06:00-Chihuahua",
  "UTC-06:00-Mountain Time US and Canada)",
  "UTC-06:00-Central America",
  "UTC-05:00-Central Time US and Canada)	",
  "UTC-05:00-Guadalajara",
  "UTC-06:00-Saskatchewan",
  "UTC-05:00-Bogota",
  "UTC-05:00-Kingston",
  "UTC-04:00-Eastern Time US and Canada)",
  "UTC-04:00-Indiana East)",
  "UTC-04:30-Caracas",
  "UTC-03:00-Asuncion",
  "UTC-03:00-Atlantic Time Canada)",
  "UTC-04:00-Cuiaba",
  "UTC-04:00-Georgetown",
  "UTC-02:30-Newfoundland and Labrador",
  "UTC-03:00-Brasilia",
  "UTC-03:00-Buenos Aires",
  "UTC-03:00-Cayenne",
  "UTC-02:00-Greenland",
  "UTC-03:00-Montevide",
  "UTC-03:00-Salvador",
  "UTC-03:00-Santiago",
  "UTC-02:00-Mid-Atlantic",
  "UTC+00:00-Azores",
  "UTC-01:00-Cape Verde Islands",
  "UTC+01:00-Dublin",
  "UTC+01:00-Casablanca",
  "UTC+00:00-Monrovia",
  "UTC+02:00-Amsterdam",
  "UTC+02:00-Belgrade",
  "UTC+02:00-Brussels",
  "UTC+02:00-Sarajevo",
  "UTC+01:00-West Central Africa",
  "UTC+02:00-Windhoek",
  "UTC+03:00-Athen",
  "UTC+03:00-Beirut",
  "UTC+02:00-Cairo",
  "UTC+03:00-Damascus",
  "UTC+03:00-Eastern Europe",
  "UTC+02:00-Harare",
  "UTC+03:00-Helsinki",
  "UTC+03:00-Istanbul",
  "UTC+03:00-Jerusalem",
  "UTC+02:00-Kaliningrad",
  "UTC+02:00-Tripoli",
  "UTC+03:00-Amman",
  "UTC+03:00-Baghdad",
  "UTC+03:00-Kuwait",
  "UTC+03:00-Minsk",
  "UTC+03:00-Moscow",
  "UTC+03:00-Nairobi",
  "UTC+03:30-Tehran",
  "UTC+04:00-Abu Dhabi",
  "UTC+05:00-Baku",
  "UTC+04:00-Izhevsk",
  "UTC+04:00-Port Louis",
  "UTC+04:00-Tbilisi",
  "UTC+04:00-Yerevan",
  "UTC+04:30-Kabul",
  "UTC+05:00-Tashkent",
  "UTC+05:00-Ekaterinburg",
  "UTC+05:00-Islamabad",
  "UTC+05:30-Chennai",
  "UTC+05:30-Sri Jayawardenepura",
  "UTC+05:45-Kathmandu",
  "UTC+06:00-Astana",
  "UTC+06:00-Dhaka",
  "UTC+06:00-Novosibirsk",
  "UTC+06:30-Yangon Rangoon",
  "UTC+07:00-Bangkok",
  "UTC+07:00-Krasnoyarsk",
  "UTC+08:00-Beijing",
  "UTC+08:00-Irkutsk",
  "UTC+08:00-Kuala Lumpur",
  "UTC+08:00-Perth",
  "UTC+08:00-Taipei",
  "UTC+08:00-Ulaanbaatar",
  "UTC+09:00-Osaka",
  "UTC+09:00-Seoul",
  "UTC+09:00-Yakutsk",
  "UTC+10:30-Adelaide",
  "UTC+09:30-Darwin",
  "UTC+10:00-Brisbane",
  "UTC+11:00-Canberra",
  "UTC+10:00-Guam",
  "UTC+11:00-Hobart",
  "UTC+10:00-Magadan",
  "UTC+10:00-Vladivostok",
  "UTC+11:00-Chokirdakh",
  "UTC+11:00-Solomon Islands",
  "UTC+12:00-Anadyr",
  "UTC+13:00-Auckland",
  "UTC+12:00-Fiji Islands",
  "UTC+13:00-Nukualofa",
  "UTC+14:00-Samoa",
];