export const CURRENCY_WITH_CODE = [
  { name: "Afghan Afghani", code: "AFA" },
  { name: "Albanian Lek", code: "ALL" },
  { name: "Algerian Dinar", code: "DZD" },
  { name: "Angolan Kwanza", code: "AOA" },
  { name: "Argentine Peso", code: "ARS" },
  { name: "Armenian Dram", code: "AMD" },
  { name: "Aruban Florin", code: "AWG" },
  { name: "Australian Dollar", code: "AUD" },
  { name: "Azerbaijani Manat", code: "AZN" },
  { name: "Bahamian Dollar", code: "BSD" },
  { name: "Bahraini Dinar", code: "BHD" },
  { name: "Bangladeshi Taka", code: "BDT" },
  { name: "Barbadian Dollar", code: "BBD" },
  { name: "Belarusian Ruble", code: "BYR" },
  { name: "Belgian Franc", code: "BEF" },
  { name: "Belize Dollar", code: "BZD" },
  { name: "Bermudan Dollar", code: "BMD" },
  { name: "Bhutanese Ngultrum", code: "BTN" },
  { name: "Bitcoin", code: "BTC" },
  { name: "Bolivian Boliviano", code: "BOB" },
  { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM" },
  { name: "Botswanan Pula", code: "BWP" },
  { name: "Brazilian Real", code: "BRL" },
  { name: "British Pound Sterling", code: "GBP" },
  { name: "Brunei Dollar", code: "BND" },
  { name: "Bulgarian Lev", code: "BGN" },
  { name: "Burundian Franc", code: "BIF" },
  { name: "Cambodian Riel", code: "KHR" },
  { name: "Canadian Dollar", code: "CAD" },
  { name: "Cape Verdean Escudo", code: "CVE" },
  { name: "Cayman Islands Dollar", code: "KYD" },
  { name: "CFA Franc BCEAO", code: "XOF" },
  { name: "CFA Franc BEAC", code: "XAF" },
  { name: "CFP Franc", code: "XPF" },
  { name: "Chilean Peso", code: "CLP" },
  { name: "Chilean Unit of Account", code: "CLF" },
  { name: "Chinese Yuan", code: "CNY" },
  { name: "Colombian Peso", code: "COP" },
  { name: "Comorian Franc", code: "KMF" },
  { name: "Congolese Franc", code: "CDF" },
  { name: "Costa Rican Colón", code: "CRC" },
  { name: "Croatian Kuna", code: "HRK" },
  { name: "Cuban Convertible Peso", code: "CUC" },
  { name: "Czech Republic Koruna", code: "CZK" },
  { name: "Danish Krone", code: "DKK" },
  { name: "Djiboutian Franc", code: "DJF" },
  { name: "Dominican Peso", code: "DOP" },
  { name: "East Caribbean Dollar", code: "XCD" },
  { name: "Egyptian Pound", code: "EGP" },
  { name: "Eritrean Nakfa", code: "ERN" },
  { name: "Estonian Kroon", code: "EEK" },
  { name: "Ethiopian Birr", code: "ETB" },
  { name: "Euro", code: "EUR" },
  { name: "Falkland Islands Pound", code: "FKP" },
  { name: "Fijian Dollar", code: "FJD" },
  { name: "Gambian Dalasi", code: "GMD" },
  { name: "Georgian Lari", code: "GEL" },
  { name: "German Mark", code: "DEM" },
  { name: "Ghanaian Cedi", code: "GHS" },
  { name: "Gibraltar Pound", code: "GIP" },
  { name: "Greek Drachma", code: "GRD" },
  { name: "Guatemalan Quetzal", code: "GTQ" },
  { name: "Guinean Franc", code: "GNF" },
  { name: "Guyanaese Dollar", code: "GYD" },
  { name: "Haitian Gourde", code: "HTG" },
  { name: "Honduran Lempira", code: "HNL" },
  { name: "Hong Kong Dollar", code: "HKD" },
  { name: "Hungarian Forint", code: "HUF" },
  { name: "Icelandic Króna", code: "ISK" },
  { name: "Indian Rupee", code: "INR" },
  { name: "Indonesian Rupiah", code: "IDR" },
  { name: "Iranian Rial", code: "IRR" },
  { name: "Iraqi Dinar", code: "IQD" },
  { name: "Israeli New Sheqel", code: "ILS" },
  { name: "Italian Lira", code: "ITL" },
  { name: "Jamaican Dollar", code: "JMD" },
  { name: "Japanese Yen", code: "JPY" },
  { name: "Jordanian Dinar", code: "JOD" },
  { name: "Kazakhstani Tenge", code: "KZT" },
  { name: "Kenyan Shilling", code: "KES" },
  { name: "Kuwaiti Dinar", code: "KWD" },
  { name: "Kyrgystani Som", code: "KGS" },
  { name: "Laotian Kip", code: "LAK" },
  { name: "Latvian Lats", code: "LVL" },
  { name: "Lebanese Pound", code: "LBP" },
  { name: "Lesotho Loti", code: "LSL" },
  { name: "Liberian Dollar", code: "LRD" },
  { name: "Libyan Dinar", code: "LYD" },
  { name: "Litecoin", code: "LTC" },
  { name: "Lithuanian Litas", code: "LTL" },
  { name: "Macanese Pataca", code: "MOP" },
  { name: "Macedonian Denar", code: "MKD" },
  { name: "Malagasy Ariary", code: "MGA" },
  { name: "Malawian Kwacha", code: "MWK" },
  { name: "Malaysian Ringgit", code: "MYR" },
  { name: "Maldivian Rufiyaa", code: "MVR" },
  { name: "Mauritanian Ouguiya", code: "MRO" },
  { name: "Mauritian Rupee", code: "MUR" },
  { name: "Mexican Peso", code: "MXN" },
  { name: "Moldovan Leu", code: "MDL" },
  { name: "Mongolian Tugrik", code: "MNT" },
  { name: "Moroccan Dirham", code: "MAD" },
  { name: "Mozambican Metical", code: "MZM" },
  { name: "Myanmar Kyat", code: "MMK" },
  { name: "Namibian Dollar", code: "NAD" },
  { name: "Nepalese Rupee", code: "NPR" },
  { name: "Netherlands Antillean Guilder", code: "ANG" },
  { name: "New Taiwan Dollar", code: "TWD" },
  { name: "New Zealand Dollar", code: "NZD" },
  { name: "Nicaraguan Córdoba", code: "NIO" },
  { name: "Nigerian Naira", code: "NGN" },
  { name: "North Korean Won", code: "KPW" },
  { name: "Norwegian Krone", code: "NOK" },
  { name: "Omani Rial", code: "OMR" },
  { name: "Pakistani Rupee", code: "PKR" },
  { name: "Panamanian Balboa", code: "PAB" },
  { name: "Papua New Guinean Kina", code: "PGK" },
  { name: "Paraguayan Guarani", code: "PYG" },
  { name: "Peruvian Nuevo Sol", code: "PEN" },
  { name: "Philippine Peso", code: "PHP" },
  { name: "Polish Zloty", code: "PLN" },
  { name: "Qatari Rial", code: "QAR" },
  { name: "Romanian Leu", code: "RON" },
  { name: "Russian Ruble", code: "RUB" },
  { name: "Rwandan Franc", code: "RWF" },
  { name: "Salvadoran Colón", code: "SVC" },
  { name: "Samoan Tala", code: "WST" },
  { name: "São Tomé and Príncipe Dobra", code: "STD" },
  { name: "Saudi Riyal", code: "SAR" },
  { name: "Serbian Dinar", code: "RSD" },
  { name: "Seychellois Rupee", code: "SCR" },
  { name: "Sierra Leonean Leone", code: "SLL" },
  { name: "Singapore Dollar", code: "SGD" },
  { name: "Slovak Koruna", code: "SKK" },
  { name: "Solomon Islands Dollar", code: "SBD" },
  { name: "Somali Shilling", code: "SOS" },
  { name: "South African Rand", code: "ZAR" },
  { name: "South Korean Won", code: "KRW" },
  { name: "South Sudanese Pound", code: "SSP" },
  { name: "Special Drawing Rights", code: "XDR" },
  { name: "Sri Lankan Rupee", code: "LKR" },
  { name: "St. Helena Pound", code: "SHP" },
  { name: "Sudanese Pound", code: "SDG" },
  { name: "Surinamese Dollar", code: "SRD" },
  { name: "Swazi Lilangeni", code: "SZL" },
  { name: "Swedish Krona", code: "SEK" },
  { name: "Swiss Franc", code: "CHF" },
  { name: "Syrian Pound", code: "SYP" },
  { name: "Tajikistani Somoni", code: "TJS" },
  { name: "Tanzanian Shilling", code: "TZS" },
  { name: "Thai Baht", code: "THB" },
  { name: "Tongan Pa'anga", code: "TOP" },
  { name: "Trinidad & Tobago Dollar", code: "TTD" },
  { name: "Tunisian Dinar", code: "TND" },
  { name: "Turkish Lira", code: "TRY" },
  { name: "Turkmenistani Manat", code: "TMT" },
  { name: "Ugandan Shilling", code: "UGX" },
  { name: "Ukrainian Hryvnia", code: "UAH" },
  { name: "United Arab Emirates Dirham", code: "AED" },
  { name: "Uruguayan Peso", code: "UYU" },
  { name: "US Dollar", code: "USD" },
  { name: "Uzbekistan Som", code: "UZS" },
  { name: "Vanuatu Vatu", code: "VUV" },
  { name: "Venezuelan BolÃvar", code: "VEF" },
  { name: "Vietnamese Dong", code: "VND" },
  { name: "Yemeni Rial", code: "YER" },
  { name: "Zambian Kwacha", code: "ZMK" },
  { name: "Zimbabwean dollar", code: "ZWL" },
];

export const CURRENCY = [
  { country: "Afghan Afghani", symbol: "؋" },
  { country: "Albanian Lek", symbol: "Lek" },
  { country: "Algerian Dinar", symbol: "دج" },
  { country: "Angolan Kwanza", symbol: "Kz" },
  { country: "Argentine Peso", symbol: "$" },
  { country: "Armenian Dram", symbol: "֏" },
  { country: "Aruban Florin", symbol: "ƒ" },
  { country: "Australian Dollar", symbol: "$" },
  { country: "Azerbaijani Manat", symbol: "m" },
  { country: "Bahamian Dollar", symbol: "B$" },
  { country: "Bahraini Dinar", symbol: ".د.ب" },
  { country: "Bangladeshi Taka", symbol: "৳" },
  { country: "Barbadian Dollar", symbol: "Bds$" },
  { country: "Belarusian Ruble", symbol: "Br" },
  { country: "Belgian Franc", symbol: "fr" },
  { country: "Belize Dollar", symbol: "$" },
  { country: "Bermudan Dollar", symbol: "$" },
  { country: "Bhutanese Ngultrum", symbol: "Nu." },
  { country: "Bitcoin", symbol: "฿" },
  { country: "Bolivian Boliviano", symbol: "Bs." },
  { country: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { country: "Botswanan Pula", symbol: "P" },
  { country: "Brazilian Real", symbol: "R$" },
  { country: "British Pound Sterling", symbol: "£" },
  { country: "Brunei Dollar", symbol: "B$" },
  { country: "Bulgarian Lev", symbol: "Лв." },
  { country: "Burundian Franc", symbol: "FBu" },
  { country: "Cambodian Riel", symbol: "KHR" },
  { country: "Canadian Dollar", symbol: "$" },
  { country: "Cape Verdean Escudo", symbol: "$" },
  { country: "Cayman Islands Dollar", symbol: "$" },
  { country: "CFA Franc BCEAO", symbol: "CFA" },
  { country: "CFA Franc BEAC", symbol: "FCFA" },
  { country: "CFP Franc", symbol: "₣" },
  { country: "Chilean Peso", symbol: "$" },
  { country: "Chinese Yuan", symbol: "¥" },
  { country: "Colombian Peso", symbol: "$" },
  { country: "Comorian Franc", symbol: "CF" },
  { country: "Congolese Franc", symbol: "FC" },
  { country: "Costa Rican ColÃ³n", symbol: "₡" },
  { country: "Croatian Kuna", symbol: "kn" },
  { country: "Cuban Convertible Peso", symbol: "$CUC" },
  { country: "Czech Republic Koruna", symbol: "Kč" },
  { country: "Danish Krone", symbol: "Kr." },
  { country: "Djiboutian Franc", symbol: "Fdj" },
  { country: "Dominican Peso", symbol: "$" },
  { country: "East Caribbean Dollar", symbol: "$" },
  { country: "Egyptian Pound", symbol: "ج.م" },
  { country: "Eritrean Nakfa", symbol: "Nfk" },
  { country: "Estonian Kroon", symbol: "kr" },
  { country: "Ethiopian Birr", symbol: "Nkf" },
  { country: "Euro", symbol: "€" },
  { country: "Falkland Islands Pound", symbol: "£" },
  { country: "Fijian Dollar", symbol: "FJ$" },
  { country: "Gambian Dalasi", symbol: "D" },
  { country: "Georgian Lari", symbol: "ლ" },
  { country: "German Mark", symbol: "DM" },
  { country: "Ghanaian Cedi", symbol: "GH₵" },
  { country: "Gibraltar Pound", symbol: "£" },
  { country: "Greek Drachma", symbol: "₯, Δρχ, Δρ" },
  { country: "Guatemalan Quetzal", symbol: "Q" },
  { country: "Guinean Franc", symbol: "FG" },
  { country: "Guyanaese Dollar", symbol: "$" },
  { country: "Haitian Gourde", symbol: "G" },
  { country: "Honduran Lempira", symbol: "L" },
  { country: "Hong Kong Dollar", symbol: "$" },
  { country: "Hungarian Forint", symbol: "Ft" },
  { country: "Icelandic Króna", symbol: "kr" },
  { country: "Indian Rupee", symbol: "₹" },
  { country: "Indonesian Rupiah", symbol: "Rp" },
  { country: "Iranian Rial", symbol: "﷼" },
  { country: "Iraqi Dinar", symbol: "د.ع" },
  { country: "Israeli New Sheqel", symbol: "₪" },
  { country: "Italian Lira", symbol: "L,£" },
  { country: "Jamaican Dollar", symbol: "J$" },
  { country: "Japanese Yen", symbol: "¥" },
  { country: "Jordanian Dinar", symbol: "ا.د" },
  { country: "Kazakhstani Tenge", symbol: "лв" },
  { country: "Kenyan Shilling", symbol: "KSh" },
  { country: "Kuwaiti Dinar", symbol: "ك.د" },
  { country: "Kyrgystani Som", symbol: "лв" },
  { country: "Laotian Kip", symbol: "₭" },
  { country: "Latvian Lats", symbol: "Ls" },
  { country: "Lebanese Pound", symbol: "£" },
  { country: "Lesotho Loti", symbol: "L" },
  { country: "Liberian Dollar", symbol: "$" },
  { country: "Libyan Dinar", symbol: "د.ل" },
  { country: "Lithuanian Litas", symbol: "Lt" },
  { country: "Macanese Pataca", symbol: "$" },
  { country: "Macedonian Denar", symbol: "ден" },
  { country: "Malagasy Ariary", symbol: "Ar" },
  { country: "Malawian Kwacha", symbol: "MK" },
  { country: "Malaysian Ringgit", symbol: "RM" },
  { country: "Maldivian Rufiyaa", symbol: "Rf" },
  { country: "Mauritanian Ouguiya", symbol: "MRU" },
  { country: "Mauritian Rupee", symbol: "₨" },
  { country: "Mexican Peso", symbol: "$" },
  { country: "Moldovan Leu", symbol: "L" },
  { country: "Mongolian Tugrik", symbol: "₮" },
  { country: "Moroccan Dirham", symbol: "MAD" },
  { country: "Mozambican Metical", symbol: "MT" },
  { country: "Myanmar Kyat", symbol: "K" },
  { country: "Namibian Dollar", symbol: "$" },
  { country: "Nepalese Rupee", symbol: "₨" },
  { country: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { country: "New Taiwan Dollar", symbol: "$" },
  { country: "New Zealand Dollar", symbol: "$" },
  { country: "Nicaraguan CÃ³rdoba", symbol: "C$" },
  { country: "Nigerian Naira", symbol: "₦" },
  { country: "North Korean Won", symbol: "₩" },
  { country: "Norwegian Krone", symbol: "kr" },
  { country: "Omani Rial", symbol: ".ع.ر" },
  { country: "Pakistani Rupee", symbol: "₨" },
  { country: "Panamanian Balboa", symbol: "B/." },
  { country: "Papua New Guinean Kina", symbol: "K" },
  { country: "Paraguayan Guarani", symbol: "₲" },
  { country: "Peruvian Nuevo Sol", symbol: "S/." },
  { country: "Philippine Peso", symbol: "₱" },
  { country: "Polish Zloty", symbol: "zł" },
  { country: "Qatari Rial", symbol: "ق.ر" },
  { country: "Romanian Leu", symbol: "lei" },
  { country: "Russian Ruble", symbol: "₽" },
  { country: "Rwandan Franc", symbol: "FRw" },
  { country: "Salvadoran ColÃ³n", symbol: "₡" },
  { country: "Samoan Tala", symbol: "SAT" },
  { country: "Saudi Riyal", symbol: "﷼" },
  { country: "Serbian Dinar", symbol: "din" },
  { country: "Seychellois Rupee", symbol: "SRe" },
  { country: "Sierra Leonean Leone", symbol: "Le" },
  { country: "Singapore Dollar", symbol: "$" },
  { country: "Slovak Koruna", symbol: "Sk" },
  { country: "Solomon Islands Dollar", symbol: "Si$" },
  { country: "Somali Shilling", symbol: "Sh.so." },
  { country: "South African Rand", symbol: "R" },
  { country: "South Korean Won", symbol: "₩" },
  { country: "Special Drawing Rights", symbol: "SDR" },
  { country: "Sri Lankan Rupee", symbol: "Rs" },
  { country: "St. Helena Pound", symbol: "£" },
  { country: "Sudanese Pound", symbol: ".س.ج" },
  { country: "Surinamese Dollar", symbol: "$" },
  { country: "Swazi Lilangeni", symbol: "E" },
  { country: "Swedish Krona", symbol: "kr" },
  { country: "Swiss Franc", symbol: "CHf" },
  { country: "Syrian Pound", symbol: "LS" },
  { country: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { country: "Tajikistani Somoni", symbol: "SM" },
  { country: "Tanzanian Shilling", symbol: "TSh" },
  { country: "Thai Baht", symbol: "฿" },
  { country: "Tongan Pa'anga", symbol: "$" },
  { country: "Trinidad & Tobago Dollar", symbol: "$" },
  { country: "Tunisian Dinar", symbol: "ت.د" },
  { country: "Turkish Lira", symbol: "₺" },
  { country: "Turkmenistani Manat", symbol: "T" },
  { country: "Ugandan Shilling", symbol: "USh" },
  { country: "Ukrainian Hryvnia", symbol: "₴" },
  { country: "United Arab Emirates Dirham", symbol: "إ.د" },
  { country: "Uruguayan Peso", symbol: "$" },
  { country: "US Dollar", symbol: "$" },
  { country: "Uzbekistan Som", symbol: "лв" },
  { country: "Vanuatu Vatu", symbol: "VT" },
  { country: "Venezuelan BolÃvar", symbol: "Bs" },
  { country: "Vietnamese Dong", symbol: "₫" },
  { country: "Yemeni Rial", symbol: "﷼" },
  { country: "Zambian Kwacha", symbol: "ZK" },
];

export const currency = [
  { name: "Afghan Afghani", code: "AFA" },
  { name: "Albanian Lek", code: "ALL" },
  { name: "Algerian Dinar", code: "DZD" },
  { name: "Angolan Kwanza", code: "AOA" },
  { name: "Argentine Peso", code: "ARS" },
  { name: "Armenian Dram", code: "AMD" },
  { name: "Aruban Florin", code: "AWG" },
  { name: "Australian Dollar", code: "AUD" },
  { name: "Azerbaijani Manat", code: "AZN" },
  { name: "Bahamian Dollar", code: "BSD" },
  { name: "Bahraini Dinar", code: "BHD" },
  { name: "Bangladeshi Taka", code: "BDT" },
  { name: "Barbadian Dollar", code: "BBD" },
  { name: "Belarusian Ruble", code: "BYR" },
  { name: "Belgian Franc", code: "BEF" },
  { name: "Belize Dollar", code: "BZD" },
  { name: "Bermudan Dollar", code: "BMD" },
  { name: "Bhutanese Ngultrum", code: "BTN" },
  { name: "Bitcoin", code: "BTC" },
  { name: "Bolivian Boliviano", code: "BOB" },
  { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM" },
  { name: "Botswanan Pula", code: "BWP" },
  { name: "Brazilian Real", code: "BRL" },
  { name: "British Pound Sterling", code: "GBP" },
  { name: "Brunei Dollar", code: "BND" },
  { name: "Bulgarian Lev", code: "BGN" },
  { name: "Burundian Franc", code: "BIF" },
  { name: "Cambodian Riel", code: "KHR" },
  { name: "Canadian Dollar", code: "CAD" },
  { name: "Cape Verdean Escudo", code: "CVE" },
  { name: "Cayman Islands Dollar", code: "KYD" },
  { name: "CFA Franc BCEAO", code: "XOF" },
  { name: "CFA Franc BEAC", code: "XAF" },
  { name: "CFP Franc", code: "XPF" },
  { name: "Chilean Peso", code: "CLP" },
  { name: "Chilean Unit of Account", code: "CLF" },
  { name: "Chinese Yuan", code: "CNY" },
  { name: "Colombian Peso", code: "COP" },
  { name: "Comorian Franc", code: "KMF" },
  { name: "Congolese Franc", code: "CDF" },
  { name: "Costa Rican Colón", code: "CRC" },
  { name: "Croatian Kuna", code: "HRK" },
  { name: "Cuban Convertible Peso", code: "CUC" },
  { name: "Czech Republic Koruna", code: "CZK" },
  { name: "Danish Krone", code: "DKK" },
  { name: "Djiboutian Franc", code: "DJF" },
  { name: "Dominican Peso", code: "DOP" },
  { name: "East Caribbean Dollar", code: "XCD" },
  { name: "Egyptian Pound", code: "EGP" },
  { name: "Eritrean Nakfa", code: "ERN" },
  { name: "Estonian Kroon", code: "EEK" },
  { name: "Ethiopian Birr", code: "ETB" },
  { name: "Euro", code: "EUR" },
  { name: "Falkland Islands Pound", code: "FKP" },
  { name: "Fijian Dollar", code: "FJD" },
  { name: "Gambian Dalasi", code: "GMD" },
  { name: "Georgian Lari", code: "GEL" },
  { name: "German Mark", code: "DEM" },
  { name: "Ghanaian Cedi", code: "GHS" },
  { name: "Gibraltar Pound", code: "GIP" },
  { name: "Greek Drachma", code: "GRD" },
  { name: "Guatemalan Quetzal", code: "GTQ" },
  { name: "Guinean Franc", code: "GNF" },
  { name: "Guyanaese Dollar", code: "GYD" },
  { name: "Haitian Gourde", code: "HTG" },
  { name: "Honduran Lempira", code: "HNL" },
  { name: "Hong Kong Dollar", code: "HKD" },
  { name: "Hungarian Forint", code: "HUF" },
  { name: "Icelandic Króna", code: "ISK" },
  { name: "Indian Rupee", code: "INR" },
  { name: "Indonesian Rupiah", code: "IDR" },
  { name: "Iranian Rial", code: "IRR" },
  { name: "Iraqi Dinar", code: "IQD" },
  { name: "Israeli New Sheqel", code: "ILS" },
  { name: "Italian Lira", code: "ITL" },
  { name: "Jamaican Dollar", code: "JMD" },
  { name: "Japanese Yen", code: "JPY" },
  { name: "Jordanian Dinar", code: "JOD" },
  { name: "Kazakhstani Tenge", code: "KZT" },
  { name: "Kenyan Shilling", code: "KES" },
  { name: "Kuwaiti Dinar", code: "KWD" },
  { name: "Kyrgystani Som", code: "KGS" },
  { name: "Laotian Kip", code: "LAK" },
  { name: "Latvian Lats", code: "LVL" },
  { name: "Lebanese Pound", code: "LBP" },
  { name: "Lesotho Loti", code: "LSL" },
  { name: "Liberian Dollar", code: "LRD" },
  { name: "Libyan Dinar", code: "LYD" },
  { name: "Litecoin", code: "LTC" },
  { name: "Lithuanian Litas", code: "LTL" },
  { name: "Macanese Pataca", code: "MOP" },
  { name: "Macedonian Denar", code: "MKD" },
  { name: "Malagasy Ariary", code: "MGA" },
  { name: "Malawian Kwacha", code: "MWK" },
  { name: "Malaysian Ringgit", code: "MYR" },
  { name: "Maldivian Rufiyaa", code: "MVR" },
  { name: "Mauritanian Ouguiya", code: "MRO" },
  { name: "Mauritian Rupee", code: "MUR" },
  { name: "Mexican Peso", code: "MXN" },
  { name: "Moldovan Leu", code: "MDL" },
  { name: "Mongolian Tugrik", code: "MNT" },
  { name: "Moroccan Dirham", code: "MAD" },
  { name: "Mozambican Metical", code: "MZM" },
  { name: "Myanmar Kyat", code: "MMK" },
  { name: "Namibian Dollar", code: "NAD" },
  { name: "Nepalese Rupee", code: "NPR" },
  { name: "Netherlands Antillean Guilder", code: "ANG" },
  { name: "New Taiwan Dollar", code: "TWD" },
  { name: "New Zealand Dollar", code: "NZD" },
  { name: "Nicaraguan Córdoba", code: "NIO" },
  { name: "Nigerian Naira", code: "NGN" },
  { name: "North Korean Won", code: "KPW" },
  { name: "Norwegian Krone", code: "NOK" },
  { name: "Omani Rial", code: "OMR" },
  { name: "Pakistani Rupee", code: "PKR" },
  { name: "Panamanian Balboa", code: "PAB" },
  { name: "Papua New Guinean Kina", code: "PGK" },
  { name: "Paraguayan Guarani", code: "PYG" },
  { name: "Peruvian Nuevo Sol", code: "PEN" },
  { name: "Philippine Peso", code: "PHP" },
  { name: "Polish Zloty", code: "PLN" },
  { name: "Qatari Rial", code: "QAR" },
  { name: "Romanian Leu", code: "RON" },
  { name: "Russian Ruble", code: "RUB" },
  { name: "Rwandan Franc", code: "RWF" },
  { name: "Salvadoran Colón", code: "SVC" },
  { name: "Samoan Tala", code: "WST" },
  { name: "São Tomé and Príncipe Dobra", code: "STD" },
  { name: "Saudi Riyal", code: "SAR" },
  { name: "Serbian Dinar", code: "RSD" },
  { name: "Seychellois Rupee", code: "SCR" },
  { name: "Sierra Leonean Leone", code: "SLL" },
  { name: "Singapore Dollar", code: "SGD" },
  { name: "Slovak Koruna", code: "SKK" },
  { name: "Solomon Islands Dollar", code: "SBD" },
  { name: "Somali Shilling", code: "SOS" },
  { name: "South African Rand", code: "ZAR" },
  { name: "South Korean Won", code: "KRW" },
  { name: "South Sudanese Pound", code: "SSP" },
  { name: "Special Drawing Rights", code: "XDR" },
  { name: "Sri Lankan Rupee", code: "LKR" },
  { name: "St. Helena Pound", code: "SHP" },
  { name: "Sudanese Pound", code: "SDG" },
  { name: "Surinamese Dollar", code: "SRD" },
  { name: "Swazi Lilangeni", code: "SZL" },
  { name: "Swedish Krona", code: "SEK" },
  { name: "Swiss Franc", code: "CHF" },
  { name: "Syrian Pound", code: "SYP" },
  { name: "Tajikistani Somoni", code: "TJS" },
  { name: "Tanzanian Shilling", code: "TZS" },
  { name: "Thai Baht", code: "THB" },
  { name: "Tongan Pa'anga", code: "TOP" },
  { name: "Trinidad & Tobago Dollar", code: "TTD" },
  { name: "Tunisian Dinar", code: "TND" },
  { name: "Turkish Lira", code: "TRY" },
  { name: "Turkmenistani Manat", code: "TMT" },
  { name: "Ugandan Shilling", code: "UGX" },
  { name: "Ukrainian Hryvnia", code: "UAH" },
  { name: "United Arab Emirates Dirham", code: "AED" },
  { name: "Uruguayan Peso", code: "UYU" },
  { name: "US Dollar", code: "USD" },
  { name: "Uzbekistan Som", code: "UZS" },
  { name: "Vanuatu Vatu", code: "VUV" },
  { name: "Venezuelan BolÃvar", code: "VEF" },
  { name: "Vietnamese Dong", code: "VND" },
  { name: "Yemeni Rial", code: "YER" },
  { name: "Zambian Kwacha", code: "ZMK" },
  { name: "Zimbabwean dollar", code: "ZWL" },
];

export const INDIAN_CURRENCY = { country: "Indian Rupee", symbol: "₹" };
export const COMMON_CURRENCIES = [
  { country: "Indian Rupee", symbol: "₹" },
  { country: "Australian Dollar", symbol: "$" },
  { country: "Singapore Dollar", symbol: "$" },
  { country: "US Dollar", symbol: "$" },
  { country: "Euro", symbol: "€" },
  { country: "British Pound Sterling", symbol: "£" },
];

export const OTHER_CURRENCIES = [
  { country: "Afghan Afghani", symbol: "؋" },
  { country: "Albanian Lek", symbol: "Lek" },
  { country: "Algerian Dinar", symbol: "دج" },
  { country: "Angolan Kwanza", symbol: "Kz" },
  { country: "Argentine Peso", symbol: "$" },
  { country: "Armenian Dram", symbol: "֏" },
  { country: "Aruban Florin", symbol: "ƒ" },
  { country: "Azerbaijani Manat", symbol: "m" },
  { country: "Bahamian Dollar", symbol: "B$" },
  { country: "Bahraini Dinar", symbol: ".د.ب" },
  { country: "Bangladeshi Taka", symbol: "৳" },
  { country: "Barbadian Dollar", symbol: "Bds$" },
  { country: "Belarusian Ruble", symbol: "Br" },
  { country: "Belgian Franc", symbol: "fr" },
  { country: "Belize Dollar", symbol: "$" },
  { country: "Bermudan Dollar", symbol: "$" },
  { country: "Bhutanese Ngultrum", symbol: "Nu." },
  { country: "Bitcoin", symbol: "฿" },
  { country: "Bolivian Boliviano", symbol: "Bs." },
  { country: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
  { country: "Botswanan Pula", symbol: "P" },
  { country: "Brazilian Real", symbol: "R$" },
  { country: "Brunei Dollar", symbol: "B$" },
  { country: "Bulgarian Lev", symbol: "Лв." },
  { country: "Burundian Franc", symbol: "FBu" },
  { country: "Cambodian Riel", symbol: "KHR" },
  { country: "Canadian Dollar", symbol: "$" },
  { country: "Cape Verdean Escudo", symbol: "$" },
  { country: "Cayman Islands Dollar", symbol: "$" },
  { country: "CFA Franc BCEAO", symbol: "CFA" },
  { country: "CFA Franc BEAC", symbol: "FCFA" },
  { country: "CFP Franc", symbol: "₣" },
  { country: "Chilean Peso", symbol: "$" },
  { country: "Chinese Yuan", symbol: "¥" },
  { country: "Colombian Peso", symbol: "$" },
  { country: "Comorian Franc", symbol: "CF" },
  { country: "Congolese Franc", symbol: "FC" },
  { country: "Costa Rican ColÃ³n", symbol: "₡" },
  { country: "Croatian Kuna", symbol: "kn" },
  { country: "Cuban Convertible Peso", symbol: "$CUC" },
  { country: "Czech Republic Koruna", symbol: "Kč" },
  { country: "Danish Krone", symbol: "Kr." },
  { country: "Djiboutian Franc", symbol: "Fdj" },
  { country: "Dominican Peso", symbol: "$" },
  { country: "East Caribbean Dollar", symbol: "$" },
  { country: "Egyptian Pound", symbol: "ج.م" },
  { country: "Eritrean Nakfa", symbol: "Nfk" },
  { country: "Estonian Kroon", symbol: "kr" },
  { country: "Ethiopian Birr", symbol: "Nkf" },
  { country: "Falkland Islands Pound", symbol: "£" },
  { country: "Fijian Dollar", symbol: "FJ$" },
  { country: "Gambian Dalasi", symbol: "D" },
  { country: "Georgian Lari", symbol: "ლ" },
  { country: "German Mark", symbol: "DM" },
  { country: "Ghanaian Cedi", symbol: "GH₵" },
  { country: "Gibraltar Pound", symbol: "£" },
  { country: "Greek Drachma", symbol: "₯, Δρχ, Δρ" },
  { country: "Guatemalan Quetzal", symbol: "Q" },
  { country: "Guinean Franc", symbol: "FG" },
  { country: "Guyanaese Dollar", symbol: "$" },
  { country: "Haitian Gourde", symbol: "G" },
  { country: "Honduran Lempira", symbol: "L" },
  { country: "Hong Kong Dollar", symbol: "$" },
  { country: "Hungarian Forint", symbol: "Ft" },
  { country: "Icelandic KrÃ³na", symbol: "kr" },
  { country: "Indonesian Rupiah", symbol: "Rp" },
  { country: "Iranian Rial", symbol: "﷼" },
  { country: "Iraqi Dinar", symbol: "د.ع" },
  { country: "Israeli New Sheqel", symbol: "₪" },
  { country: "Italian Lira", symbol: "L,£" },
  { country: "Jamaican Dollar", symbol: "J$" },
  { country: "Japanese Yen", symbol: "¥" },
  { country: "Jordanian Dinar", symbol: "ا.د" },
  { country: "Kazakhstani Tenge", symbol: "лв" },
  { country: "Kenyan Shilling", symbol: "KSh" },
  { country: "Kuwaiti Dinar", symbol: "ك.د" },
  { country: "Kyrgystani Som", symbol: "лв" },
  { country: "Laotian Kip", symbol: "₭" },
  { country: "Latvian Lats", symbol: "Ls" },
  { country: "Lebanese Pound", symbol: "£" },
  { country: "Lesotho Loti", symbol: "L" },
  { country: "Liberian Dollar", symbol: "$" },
  { country: "Libyan Dinar", symbol: "د.ل" },
  { country: "Lithuanian Litas", symbol: "Lt" },
  { country: "Macanese Pataca", symbol: "$" },
  { country: "Macedonian Denar", symbol: "ден" },
  { country: "Malagasy Ariary", symbol: "Ar" },
  { country: "Malawian Kwacha", symbol: "MK" },
  { country: "Malaysian Ringgit", symbol: "RM" },
  { country: "Maldivian Rufiyaa", symbol: "Rf" },
  { country: "Mauritanian Ouguiya", symbol: "MRU" },
  { country: "Mauritian Rupee", symbol: "₨" },
  { country: "Mexican Peso", symbol: "$" },
  { country: "Moldovan Leu", symbol: "L" },
  { country: "Mongolian Tugrik", symbol: "₮" },
  { country: "Moroccan Dirham", symbol: "MAD" },
  { country: "Mozambican Metical", symbol: "MT" },
  { country: "Myanmar Kyat", symbol: "K" },
  { country: "Namibian Dollar", symbol: "$" },
  { country: "Nepalese Rupee", symbol: "₨" },
  { country: "Netherlands Antillean Guilder", symbol: "ƒ" },
  { country: "New Taiwan Dollar", symbol: "$" },
  { country: "New Zealand Dollar", symbol: "$" },
  { country: "Nicaraguan CÃ³rdoba", symbol: "C$" },
  { country: "Nigerian Naira", symbol: "₦" },
  { country: "North Korean Won", symbol: "₩" },
  { country: "Norwegian Krone", symbol: "kr" },
  { country: "Omani Rial", symbol: ".ع.ر" },
  { country: "Pakistani Rupee", symbol: "₨" },
  { country: "Panamanian Balboa", symbol: "B/." },
  { country: "Papua New Guinean Kina", symbol: "K" },
  { country: "Paraguayan Guarani", symbol: "₲" },
  { country: "Peruvian Nuevo Sol", symbol: "S/." },
  { country: "Philippine Peso", symbol: "₱" },
  { country: "Polish Zloty", symbol: "zł" },
  { country: "Qatari Rial", symbol: "ق.ر" },
  { country: "Romanian Leu", symbol: "lei" },
  { country: "Russian Ruble", symbol: "₽" },
  { country: "Rwandan Franc", symbol: "FRw" },
  { country: "Salvadoran ColÃ³n", symbol: "₡" },
  { country: "Samoan Tala", symbol: "SAT" },
  { country: "Saudi Riyal", symbol: "﷼" },
  { country: "Serbian Dinar", symbol: "din" },
  { country: "Seychellois Rupee", symbol: "SRe" },
  { country: "Sierra Leonean Leone", symbol: "Le" },
  { country: "Slovak Koruna", symbol: "Sk" },
  { country: "Solomon Islands Dollar", symbol: "Si$" },
  { country: "Somali Shilling", symbol: "Sh.so." },
  { country: "South African Rand", symbol: "R" },
  { country: "South Korean Won", symbol: "₩" },
  { country: "Special Drawing Rights", symbol: "SDR" },
  { country: "Sri Lankan Rupee", symbol: "Rs" },
  { country: "St. Helena Pound", symbol: "£" },
  { country: "Sudanese Pound", symbol: ".س.ج" },
  { country: "Surinamese Dollar", symbol: "$" },
  { country: "Swazi Lilangeni", symbol: "E" },
  { country: "Swedish Krona", symbol: "kr" },
  { country: "Swiss Franc", symbol: "CHf" },
  { country: "Syrian Pound", symbol: "LS" },
  { country: "São Tomé and Príncipe Dobra", symbol: "Db" },
  { country: "Tajikistani Somoni", symbol: "SM" },
  { country: "Tanzanian Shilling", symbol: "TSh" },
  { country: "Thai Baht", symbol: "฿" },
  { country: "Tongan Pa'anga", symbol: "$" },
  { country: "Trinidad & Tobago Dollar", symbol: "$" },
  { country: "Tunisian Dinar", symbol: "ت.د" },
  { country: "Turkish Lira", symbol: "₺" },
  { country: "Turkmenistani Manat", symbol: "T" },
  { country: "Ugandan Shilling", symbol: "USh" },
  { country: "Ukrainian Hryvnia", symbol: "₴" },
  { country: "United Arab Emirates Dirham", symbol: "إ.د" },
  { country: "Uruguayan Peso", symbol: "$" },
  { country: "Uzbekistan Som", symbol: "лв" },
  { country: "Vanuatu Vatu", symbol: "VT" },
  { country: "Venezuelan BolÃvar", symbol: "Bs" },
  { country: "Vietnamese Dong", symbol: "₫" },
  { country: "Yemeni Rial", symbol: "﷼" },
  { country: "Zambian Kwacha", symbol: "ZK" },
];

export const getCurrencyCode = (name) => {
  if (currency.filter((c) => c.name === name)?.length !== 0) {
    return currency.filter((c) => c.name === name)[0];
  }
};
